# jdbc_config datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

    #.url: jdbc:oracle:thin:@localhost:1521:orcl
    #.username: scott
    #.password: scott
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
  hikari:
    minimum-idle: 3
    maximum-pool-size: 5
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    idle-timeout: 600000
    connection-timeout: 30000
    leak-detection-threshold: 120000
server:
  servlet:
    context-path: /
  port: 8090

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml